### ISSUE TITLE
Clarification of Terraform input variable dotnet-container-githash

### ISSUE THREAD

**Issue by nodesocket** [ukncsc/mail-check#3]
Can you clarify what this hash value should be? Is this the hash of the public container listed on Docker Hub for `microsoft/dotnet:2.1-sdk`?

Same question for `frontend-container-githash`?

**Comment by AlistairC-UK** [comment]
Hi, this has been documented in the readme, and also a description has been added to the terraform variable. This is present in release 1.8

**Comment by bslavin** [comment]
@AlistairC-UK what is the timeline for 1.8 ?
