### ISSUE TITLE
Terraform Variables

### ISSUE THREAD

**Issue by bslavin** [ukncsc/mail-check#6]
Other than the issues already noted these Terraform variables are hard coded 

auth-OIDC-client-secret
auth-OIDC-provider-metadata
KmsKeySource
OIDCCryptoPassphrase

**Comment by AlistairC-UK** [comment]
Hi, thanks for your comment. These variables are passed in via the environment specific tfvars file which should be kept private. Could you clarify what you mean by hard coded?
