### ISSUE TITLE
Depenencies

### ISSUE THREAD

**Issue by VasuRB** [ukncsc/mail-check#7]
The code has dependency with a library called as mail elite. This library seems to be custom made and proprietary code. Can you keep it open?. Here is the code snippet from DMARC API Controllers calling Emailelite

[HttpPatch]
        [Route("{id}/domain", Name=nameof(AddDomainsToGroup))]
        public async Task<IActionResult> AddDomainsToGroup(ChangeMembershipRequest request)
        {
            ValidationResult validationResult = _idEntityIdsRequestValidator.Validate(request);
            if (!validationResult.IsValid)
            {
                string email = User.FindFirst(_ => _.Type == ClaimTypes.Email)?.Value;
                _log.LogWarning($"User {emailelite} made bad request: {validationResult.GetErrorString()}");
                return BadRequest(validationResult.GetErrorString());
            }

            List<Tuple<int, int>> groupDomains = request.EntityIds.Select(_ => Tuple.Create(request.Id, _)).ToList();
            await _groupDomainDao.AddGroupDomains(groupDomains);

            return CreatedAtRoute(nameof(GetGroupDomains), new { request.Id }, null);
        }

**Comment by samhjohnson** [comment]
Hi @VasuRB 

Thanks for the information but if you refer to the line in Github it does not reference emailelite:

https://github.com/ukncsc/mail-check/blob/02de533900a539b0bf9a77cdc530ccc33cff07ec/src/dotnet/Dmarc/src/Dmarc.Admin.Api/Controllers/GroupContoller.cs#L140

**Comment by samhjohnson** [comment]
Closing issue as a non issue
